### PR TITLE
Change source folder to src, update tests [100% coverage]

### PR DESCRIPTION
**Pull request by f3l1x**
This PR rename /Gopay folder to /src. 

Split sources 
- `Gopay/*` to `src/Gopay/*`

Now, all tests passed, test coverage is pretty 100%. 

In the future, `GopayApi` could be standalone repository.

What do you think? @hrach  @vojtech-dobes @hranicka

### CODE REVIEW

**Comment by hranicka** [comment]
Thx for your work on the Markette/GoPay!

But maybe the change from Gopay/Api to GopayApi is unnecessary break or not?

Movement of files from Gopay/* to src/Gopay/* :+1:

**Comment by f3l1x** [comment]
I would like to split in next release GopayApi to other repo. You can then build your own wrapper on it. But I agree, it's maybe unnecessary BC break.

if you try to figure out how to exclude Gopay/Api from coverage report, I will change it.

**Comment by hranicka** [comment]
I know how to exclude files from coverage report only for [PHPUnit](https://phpunit.de/manual/current/en/code-coverage-analysis.html#code-coverage-analysis.including-excluding-files) but not for Nette Tester :(

So v3.0 will be composed from 2 repositories, Markette\Gopay and Markette\GopayApi (or something like this)?

Then I agree with namespace BC-break.
But my vote is minor.

Can you add the note to readme/changelog please?
(or I can do this)

**Comment by f3l1x** [comment]
I think it's a 2.1.0, but I'm no sure.

Maybe, I keep Gopay/Api. And split it into two packages in up-comming v3.0. What do you think?

Split into 2 packages seems to me a good move. Because, you can access only API classes and not whole service/helpers etc. Hm?

**Comment by hranicka** [comment]
I suggest 2.1.0 if it will be without BC-break (so without `Gopay/Api/*` to `src/GopayApi/*`).

3.0.0 if the BC-break remains.
Then movement GopayApi to another repo won't be next BC-break from outside the package. It will be then only internal thing.

What do you think?

Can I somehow help you with the work now?

**Comment by f3l1x** [comment]
Exactly. You hit the point. 

In other repo, it will not necessary to change namespace. If @vojtech-dobes and @hrach agree with the idea. We could, you could prepare second repo.

**Comment by f3l1x** [comment]
Basically it move sources under src directory and cover tests.

**Pull request merged**
