### PR TITLE
Service: Allow no default payment channel

### PR DESCRIPTION
**Pull request by hranicka**
This PR allows "not specify default payment channel".

Payment channel will be chosen by the GoPay itself.

### CODE REVIEW

**Comment by f3l1x** [comment]
:+1:

**Comment by f3l1x** [comment]
@hranicka Are you sure, is it possible to do that? If it's true, you could merge it.

**Comment by hranicka** [comment]
@f3l1x I did it this way on one project and it's really OK.

So you can merge it :)

(I don't like merging own PRs)

**Comment by f3l1x** [comment]
@hranicka Merged.

**Pull request merged**
