### PR TITLE
Composer: unlock for Nette >=2.2.0, <2.4.0

### PR DESCRIPTION
**Pull request by f3l1x**

### CODE REVIEW

**Comment by hrach** [comment]
Nothing against this commit, but it's not unlocking, but locking ;)

**Comment by f3l1x** [comment]
Mmmm, your maybe right. I though that ~2.2.0 is locked for only 2.2.0 to 2.2.N. :-)

**Comment by hrach** [comment]
yes, ~2.2.0 is locked to 2.2.N, but ~2.2 is locked to ~2.N.

**Comment by f3l1x** [comment]
I see, my fault.

**Pull request closed without merging**
