### PR TITLE
Tests #24

### PR DESCRIPTION
**Pull request by haltuf**
Pull request for issue #24

### CODE REVIEW

**Comment by f3l1x** [comment]
Thanks. But, there are tiny things.

* Add tests annotations - http://tester.nette.org/#toc-anotovani-testu
* Replace ` ;` for `;` (space before semicolon)
* In https://github.com/haltuf/Gopay/commit/ced318acad4800022e7393c46f00202eb7301c09, why not `$this->soap->createPayment`?
* Personally, I do not like so much this idea - https://github.com/haltuf/Gopay/commit/3a8e50bc2c6ac127f79d578b74eaf978d367378d, is there any other way? I do not know atm, `GopaySoapSingleton` some wrapper for GopaySoap, passed via constructor over DI. What do you think?

**Comment by haltuf** [comment]
- will do
 - will do
 - because I'm stupid, was for some reason thinking that you cannot call static method this way.
 - me neither, but I do not like the current solution (static method call out of nowhere) either. The reason I did it this way is to allow mocking of GopaySoap. I do not think that principally, passing some `GopaySoapSingleton` via constructor over DI would be in principal any different from passing `GopaySoap` via constructor over DI. 
Nevertheless, I can revert this commit and comment all tests that make use of this change.

**Comment by haltuf** [comment]
Done. Please note, that haltuf@3a8e50b which you disliked shouldn't be actually part of this pull request (unless I didn't screw up), it's a different branch of my fork.

**Comment by f3l1x** [comment]
interface `IGopaySoapImpl` and class `GopaySoapImpl` registred via extension with one parameter of type `GopaySoap` and one method `getGopaySoap()` or `getSoap()` or just `get()` could helps. You can easily mock it, can't you?

**Comment by haltuf** [comment]
Probably - the whole mocking thing is new for me, so I would have to try it.
Anyway, the DI you disliked in ReturnedPayment.php is not part of this PR, so I'd suggest to leave this refactoring to someone more skilfull.

**Comment by f3l1x** [comment]
You're right that major problem is in the `ReturnedPayment`. I merge it in meanwhile as a concept of tests.

**Comment by f3l1x** [comment]
Combined to one and merged. Thanks.

https://github.com/Markette/Gopay/commit/601e842a8d324f71d924eeff99c7022be4ff1145

**Pull request closed without merging**
