### PR TITLE
AbstractService->setLang() method update. 

### PR DESCRIPTION
**Pull request by camohub**
Now it does not limit the set of allowed languages. As we talk about in my issue.

### CODE REVIEW

**Comment by camohub** [comment]
Is there anybody out there?

**Comment by f3l1x** [comment]
We all are here, just be patient please. I can't merge it in this state. Can you please change it to strict defined list of languages? I can't accept it like this.

**Comment by f3l1x** [comment]
And also tests are failing here.

**Comment by camohub** [comment]
Ok I will change it to strict. But what is the problem with tests? I don't know what it means.

**Comment by camohub** [comment]
And what about change the exception to EN fallback in this method?

**Comment by camohub** [comment]
So I did another PR with strict mode for langs.

**Pull request closed without merging**
